### ISSUE TITLE
facility kpi tab: give drivers the ability to save a note for a facility when they don't get paperwork.

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/direct-delivery#208]

**Comment by jofomah** [comment]
Currently there is a note section in the KPI tab, does this ticket mean we are going to allow them to submit KPI , i.e the note section without recording any KPI, thought that is what item: 209 will be used for?

**Comment by janetbutts** [comment]
Add a button after the facility is picked "skipped" and enable a text box to appear.
